### ISSUE TITLE
Exception when adding some ingredients to a meal

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/flutter#232]
```dart

Unhandled Exception: type 'Null' is not a subtype of type 'String' in type cast
E/flutter (10078): #0      _$IngredientFromJson (package:wger/models/nutrition/ingredient.g.dart:29:24)
E/flutter (10078): #1      new Ingredient.fromJson (package:wger/models/nutrition/ingredient.dart:87:61)
E/flutter (10078): #2      NutritionPlansProvider.fetchIngredient (package:wger/providers/nutrition.dart:266:31)
E/flutter (10078): <asynchronous suspension>
E/flutter (10078): #3      NutritionPlansProvider.addMealItem (package:wger/providers/nutrition.dart:228:30)
E/flutter (10078): <asynchronous suspension>
```

**Comment by TaarnStar** [comment]
Hi, I would like to try resolve this issue, could you assign me?

**Comment by rolandgeider** [comment]
Sure! Unfortunately I can't give you a specific ingredient where this happens, but if the traceback is not enough I can try to find out
