### ISSUE TITLE
Workout days missing from android app

### ISSUE THREAD

**Issue by Jimbassfisher** [wger-project/flutter#462]
## Steps to Reproduce

1. Open the wger app
2. Attempt to expand workout or enter detailed page

**Expected results:** 
When you expand the workout or enter the detailed page, all days would be displayed
**Actual results:** 
When you expand the workout or enter the detailed page, no days are displayed
<details>
  <summary>Logs</summary>

```
```

</details>

Wger worked fine on wedensday when I used it, but as of yesterday and today, this issue has been present. I am unsure if this issue is on the app side or the server side, but on the website all days are displayed correctly. 
IDK how to get logs on Android.

**Comment by rolandgeider** [comment]
Hi! Even on the detail page? That definitely shouldn't happen. What app version are you using?

**Comment by Spiffmeister** [comment]
I'm having a similar problem, I have tried both the google play store version (including clearing data/cache) and the fdroid version.

No issues with the app last week Wednesday when I last used it.

**Comment by Jimbassfisher** [comment]
> Hi! Even on the detail page? That definitely shouldn't happen. What app version are you using?

This is on version 1.6.3 of wger. I tried both reinstalling the app, and remaking my workout plan, but the issue still persists.

**Comment by thermoscookies** [comment]
Same issue here. Version 1.6.2 android app version

**Comment by bbkz** [comment]
I am also bugged by this. It only happens if you have a workout that contains a exercise with a video reference.

So i tried to delete the video from the webinterface but got hit by maybe a other problem... is it possible my database is corrupt?

```
ERROR 2023-12-17 21:03:37,143 log Internal Server Error: /api/v2/video/160/
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "exercises_deletionlog_uuid_2b4f5ae1_uniq"
DETAIL:  Key (uuid)=(cfb72002-898f-443a-a124-a0bce8a2e6ad) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/mixins.py", line 91, in destroy
    self.perform_destroy(instance)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/mixins.py", line 95, in perform_destroy
    instance.delete()
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/base.py", line 1132, in delete
    return collector.delete()
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/deletion.py", line 463, in delete
    signals.pre_delete.send(
  File "/usr/local/lib/python3.10/dist-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/usr/local/lib/python3.10/dist-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/home/wger/src/wger/exercises/signals.py", line 141, in add_deletion_log_video
    log.save()
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.10/dist-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "exercises_deletionlog_uuid_2b4f5ae1_uniq"
DETAIL:  Key (uuid)=(cfb72002-898f-443a-a124-a0bce8a2e6ad) already exists.
```

**Comment by rolandgeider** [comment]
Have pushed a temporary fix in the backend, the new docker images are already available. In any case I'll also fix this in the app itself

**Comment by bbkz** [comment]
:gift: Thank you! Now all the workouts show again. :smile:

**Comment by sizzlesloth** [comment]
I seem to still be getting this issue. I'm using the latest wger/server docker image (using the Docker compose file from the docker repo) with the latest Flutter app as well. As soon as I add an exercise, I can't see the workout day.

I went into the container and saw that the addition of "exercise_base_uuid" was removed. I tried re-adding this, but the issue remained.

**Comment by rolandgeider** [comment]
note that we have reworked the routine models etc, closing here, if this happens again, please open a new issue
